env:
  node: true
extends: 'eslint:recommended'
plugins:
  - json
rules:
  indent:
    - error
    - 4
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
